name: Release to crates.io

on:
  push:
    tags:
      - "*.*.*"

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Install Rust toolchain
        uses: dtolnay/rust-toolchain@stable
        with:
          components: rustfmt, clippy

      - name: Rust Cache
        uses: Swatinem/rust-cache@v2

      - name: Verify tag version matches Cargo.toml
        run: |
          TAG_VERSION=${{ github.ref_name }}
          MANIFEST_VERSION=$(cargo metadata --format-version 1 | jq -r '.packages[] | select(.name == "ruster") | .version')
          if [ "$TAG_VERSION" != "$MANIFEST_VERSION" ]; then
            echo "Error: Git tag version ($TAG_VERSION) does not match Cargo.toml version ($MANIFEST_VERSION)"
            exit 1
          fi

      - name: Check formatting
        run: cargo fmt --all -- --check

      - name: Run clippy
        run: cargo clippy --all-targets --all-features

      - name: Run tests
        run: cargo test --all-targets --all-features --workspace

      - name: Build
        run: cargo build --release --all-features --workspace

      - name: Publish to crates.io
        env:
          CARGO_REGISTRY_TOKEN: ${{ secrets.CARGO_REGISTRY_TOKEN }}
        run: |
          cargo publish --workspace --no-verify
